#fm-1 troubleshooting remote license activation error
now - is this failing because of an error

or is this error saying "you're trying to do this the wrong way?"

For now I'm going with the first one and attempting GPT's next recommended set of changes it provided based on the following error:

Requesting activation (personal license)
Unclassified error occured while trying to activate license.
Exit code was: 1
Error: The process '/usr/bin/docker' failed with exit code 1